---                
- name: copy file      
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
   - name: copy file      
    #  apt:                                  
     #  update_cache: yes
    #- name: install nginx
     # apt: 

...