#---                
#- name: copy file from matser to hosts     
  #hosts: all
  #become: yes       #provide root user permission to local user                    
  #tasks:                         
   #- name: copy file      
     #copy:                                  
       #src: /root/skillected_ansible/123.txt
       #dest: /media
       #owner: ubuntu
       #group: ubuntu
       #mode: '644'
      # backup: yes  # take backup of previous content, at same destination path. 
     


---
- name: User creation & management
  hosts: all
  become: yes

  tasks:
    #- name: Create group 'evc'
      #group:
        #name: evc
        #state: present
    - name: Create user 'chetan' with specific shell
      user:
        name: chetan
        comment: "Creating chetan user"
        shell: /bin/bash
        # home: /custom/home/chetan    # Uncomment to specify a custom home directory
        #group: evc                   # Primary group ownership
        # groups: anant,tata          # Secondary (supplementary) groups
        #state: present              # Optional: ensures user exists (default)
        #state: absent               # Uncomment to delete the user
        #remove: yes                 # When deleting, remove user's home directory and mail spool
    - name: set password to chetan user
     user:
      name: chetan
      update_password: always              #update password to existing user
      #update_password: on_create          #use while creating user
      password: "{{'chetan123' | password_hash ('sha512')}}"
...