---                
- name: copy file from matser to hosts     
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
   - name: copy file      
     copy:                                  
       src: /root/skillected_ansible/123.txt
       dest: /media
       owner: ubuntu
       group: ubuntu
       mode: '644'
       backup: yes  # take backup of previous content, befoure changing file.Our file don’t have content, if we put content in the file then while executing same playbook again, system will take backup of previous file at same destination path on host where original file can be created. 
     
       
...