---                
- name: copy file from matser to hosts     
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
   - name: copy file      
      copy:                                  
       src: /root/skillected_ansible/tesfile.txt
    #- name: install nginx
     # apt: 

...