---                
- name: copy file from matser to hosts     
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
   - name: copy file      
      copy:                                  
     #  update_cache: yes
    #- name: install nginx
     # apt: 

...