---
- name: Install Apache2
  hosts: all
  become: yes

  tasks:
 #   - name: Install Apache
 #     apt:
 #       name: apache2
 #       state: present
 #     notify: Restart Apache   #once apache is instlled, notify handlers to restart the apache.

 #   - name: Ensure Apache is started and enabled
 #     service:
 #       name: apache2
 #       state: started
 #       enabled: true

   - name: Stop apache2 and disable it on boot     #stop apache2
     service:
        name: apache2
        state: stopped
        enabled: false    
   - name: Remove Apache2 package
     apt:
        name: apache2
        state: absent
        purge: yes       # Optional: also removes config files

   - name: Auto-remove unused dependencies
     apt:
        autoremove: yes    

#  handlers:
#    - name: Restart Apache
#      service:
#        name: apache2
#        state: restarted
...