---
- name: Install and configure NGINX with Firewalld
  hosts: all
  become: yes

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      notify: Restart NGINX   #once nginx installed,notifies to  handler to restart the service

    - name: Install Firewalld
      apt:
        name: firewalld
        state: present
      notify: Restart Firewalld

    - name: Start and enable Firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open HTTP port in Firewalld  #Opens port 80 (HTTP) in the firewall permanently and immediately.
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
      notify: Reload Firewalld    

    - name: Deploy NGINX config    #to define application behaour,ie security rules, resources configuration, customization, ssh , control behaviour.
      copy:
        src: nginx.conf   #Ansible to copy a file from the control server to the managed host
        dest: /etc/nginx/nginx.conf   #Destination path on hosts
      notify: Restart NGINX

   # - name: Stop NGINX service
    #  service:
     #   name: nginx
      #  state: stopped
       # enabled: false
    - name: Stop Firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: false

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted

    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded
...