---
- name: Install and configure NGINX with Firewalld
  hosts: webservers
  become: yes

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      notify: Restart NGINX

    - name: Install Firewalld
      apt:
        name: firewalld
        state: present
      notify: Restart Firewalld

    - name: Start and enable Firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Open HTTP port in Firewalld
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes
      notify: Reload Firewalld

    - name: Deploy NGINX config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted

    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded
...