---
- name: Install and configure Apache
  hosts: all
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      notify: Restart Apache

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
...