---                
- name: nginx installation playbook        
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
   # - name: update cache      
    #  apt:                                  
     #  update_cache: yes
    #- name: install nginx
     # apt: 
      #  name: nginx
       # state: present
    #- name: ensure service started
     # service: 
      #   name: nginx
       #  state: started
        # enabled: yes

    - name: stop nginx
      service:
        name: nginx
        state: stopped
        enabled: no
        

...
