---                
- name: nginx installation playbook        
  hosts: all
  become: yes       #provide root user permission to local user                    
  tasks:                         
    - name: update catche      
      apt:                                  
        update_catche: yes
    - name: install nginx
      apt: 
        name: nginx
        state: present
    - name: start nginx service
       service: 
         name: nginx
         state:
