- name: Install Apache(httpd service) on host
  hosts: all
  become: yes

  vars:
    apache_package: nginx
    apache_service: nginx

  tasks:
    - name: Install Apache package
      apt:
        name: "{{ apache_package }}"
        state: present
        update_cache: yes

    - name: Ensure Apache service is running
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true