---
- name: copy file from matser to hosts     
  hosts: all
  become: yes       

  tasks:  
  - name: Install Apache2
    apt:
     name: apache2
     state: present
     update_cache: yes

  - name: Copy index.html to web server
    copy:
     src: /root/index.html                 
     dest: /var/www/html/index.html    

  - name: Start Apache2 service
    service:
     name: apache2
     state: started
     enabled: yes
    notify: Restart Apache2
... 